on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    outputs:
      digest:
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        id: build-push
        with:
          push: true
          file: ci/Dockerfile
          tags: ${{ inputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
  provenance:
    needs:
      - build
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.9.0
    with:
      image: ${{ inputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
      private-repository: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
